'''
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
'''


def pentagon(i):
    if ((((24*i)+1)**0.5)+1) % 6 == 0:
        return True
    return False

def hexagon(i):
    if ((((8*i)+1)**0.5)+1) % 4 == 0:
        return True
    return False

n = 286

test = True

while test == True:
    tri = n*(n+1)/2
    if pentagon(tri) and hexagon(tri):
         print(tri)
         test = False
    n+=1
